# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form1.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 431, 361))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_recv = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_recv.setGeometry(QtCore.QRect(10, 20, 411, 301))
        self.textEdit_recv.setPlaceholderText("")
        self.textEdit_recv.setObjectName("textEdit_recv")
        self.cbtn_clr = QtWidgets.QCommandLinkButton(self.groupBox)
        self.cbtn_clr.setGeometry(QtCore.QRect(10, 320, 111, 41))
        self.cbtn_clr.setObjectName("cbtn_clr")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 380, 551, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_Send = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_Send.setGeometry(QtCore.QRect(10, 20, 411, 111))
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.Btn_Send = QtWidgets.QPushButton(self.groupBox_2)
        self.Btn_Send.setGeometry(QtCore.QRect(430, 100, 111, 61))
        self.Btn_Send.setObjectName("Btn_Send")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 140, 411, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 10)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 20, 111, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_GapTime = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_GapTime.setObjectName("checkBox_GapTime")
        self.verticalLayout.addWidget(self.checkBox_GapTime)
        self.checkBox_Hex = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_Hex.setObjectName("checkBox_Hex")
        self.verticalLayout.addWidget(self.checkBox_Hex)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_GapTime = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_GapTime.setObjectName("lineEdit_GapTime")
        self.horizontalLayout.addWidget(self.lineEdit_GapTime)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(560, 380, 231, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Btn_OpenTcp = QtWidgets.QPushButton(self.groupBox_3)
        self.Btn_OpenTcp.setGeometry(QtCore.QRect(10, 130, 211, 31))
        self.Btn_OpenTcp.setObjectName("Btn_OpenTcp")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_IP = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_IP.setEditable(True)
        self.comboBox_IP.setObjectName("comboBox_IP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_IP)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Port = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Port)
        self.comboBox_TCP = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_TCP.setEditable(False)
        self.comboBox_TCP.setObjectName("comboBox_TCP")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_TCP)
        self.checkBox_iot = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_iot.setObjectName("checkBox_iot")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_iot)
        self.cbx_mqtt_coap = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cbx_mqtt_coap.setObjectName("cbx_mqtt_coap")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbx_mqtt_coap)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(440, 10, 351, 361))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.cbtn_all = QtWidgets.QCommandLinkButton(self.tab_1)
        self.cbtn_all.setGeometry(QtCore.QRect(0, 300, 101, 41))
        self.cbtn_all.setObjectName("cbtn_all")
        self.listWidget_client = QtWidgets.QListWidget(self.tab_1)
        self.listWidget_client.setGeometry(QtCore.QRect(0, 10, 341, 291))
        self.listWidget_client.setObjectName("listWidget_client")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tbl_history = QtWidgets.QTableView(self.tab_2)
        self.tbl_history.setGeometry(QtCore.QRect(0, 10, 341, 321))
        self.tbl_history.setObjectName("tbl_history")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 331, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cbx_iot_platform = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.cbx_iot_platform.setObjectName("cbx_iot_platform")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbx_iot_platform)
        self.lineEdit_Prodectid = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_Prodectid.setObjectName("lineEdit_Prodectid")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Prodectid)
        self.lineEdit_deviceid = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_deviceid.setObjectName("lineEdit_deviceid")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_deviceid)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_securekey = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_securekey.setObjectName("label_securekey")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_securekey)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 120, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 160, 331, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.File_Open = QtWidgets.QAction(MainWindow)
        self.File_Open.setStatusTip("")
        self.File_Open.setObjectName("File_Open")
        self.File_Close = QtWidgets.QAction(MainWindow)
        self.File_Close.setStatusTip("")
        self.File_Close.setObjectName("File_Close")
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.File_Open)
        self.menu_F.addAction(self.File_Close)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.File_Close.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络调试工具V1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "交互数据"))
        self.cbtn_clr.setText(_translate("MainWindow", "清空数据"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据发送"))
        self.textEdit_Send.setPlaceholderText(_translate("MainWindow", "请输入要发送的内容"))
        self.Btn_Send.setText(_translate("MainWindow", "发送数据"))
        self.checkBox_GapTime.setText(_translate("MainWindow", "定时发送"))
        self.checkBox_Hex.setText(_translate("MainWindow", "发送Hex字节"))
        self.label_4.setText(_translate("MainWindow", "时间"))
        self.lineEdit_GapTime.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "ms"))
        self.groupBox_3.setTitle(_translate("MainWindow", "网络连接设置"))
        self.Btn_OpenTcp.setText(_translate("MainWindow", "打开连接"))
        self.label.setText(_translate("MainWindow", "协议类型"))
        self.label_2.setText(_translate("MainWindow", "本机地址"))
        self.label_3.setText(_translate("MainWindow", "本机端口号"))
        self.lineEdit_Port.setText(_translate("MainWindow", "9000"))
        self.checkBox_iot.setText(_translate("MainWindow", "云测试"))
        self.cbtn_all.setText(_translate("MainWindow", "全选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "客户端列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "服务器连接列表"))
        self.label_6.setText(_translate("MainWindow", "  IotPlatfrom  "))
        self.label_7.setText(_translate("MainWindow", "  ProdectId  "))
        self.label_8.setText(_translate("MainWindow", "  DeviceId  "))
        self.label_securekey.setText(_translate("MainWindow", "  SecureKey  "))
        self.radioButton.setText(_translate("MainWindow", "Hmac-SHA1"))
        self.radioButton_2.setText(_translate("MainWindow", "Hmac-SHA256"))
        self.radioButton_3.setText(_translate("MainWindow", "不使用加密协议"))
        self.groupBox_4.setTitle(_translate("MainWindow", "TopicList"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "MQTT参数"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.File_Open.setText(_translate("MainWindow", "打开"))
        self.File_Close.setText(_translate("MainWindow", "退出"))
