# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form1.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 431, 361))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_recv = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_recv.setGeometry(QtCore.QRect(10, 20, 411, 301))
        self.textEdit_recv.setPlaceholderText("")
        self.textEdit_recv.setObjectName("textEdit_recv")
        self.cbtn_clr = QtWidgets.QCommandLinkButton(self.groupBox)
        self.cbtn_clr.setGeometry(QtCore.QRect(10, 320, 111, 41))
        self.cbtn_clr.setObjectName("cbtn_clr")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 380, 551, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_Send = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_Send.setGeometry(QtCore.QRect(10, 20, 411, 111))
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.Btn_Send = QtWidgets.QPushButton(self.groupBox_2)
        self.Btn_Send.setGeometry(QtCore.QRect(430, 120, 111, 41))
        self.Btn_Send.setObjectName("Btn_Send")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 140, 411, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 10)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 20, 111, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_GapTime = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_GapTime.setObjectName("checkBox_GapTime")
        self.verticalLayout.addWidget(self.checkBox_GapTime)
        self.checkBox_Hex = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_Hex.setObjectName("checkBox_Hex")
        self.verticalLayout.addWidget(self.checkBox_Hex)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_GapTime = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_GapTime.setObjectName("lineEdit_GapTime")
        self.horizontalLayout.addWidget(self.lineEdit_GapTime)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(560, 380, 231, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Btn_OpenTcp = QtWidgets.QPushButton(self.groupBox_3)
        self.Btn_OpenTcp.setGeometry(QtCore.QRect(10, 120, 211, 41))
        self.Btn_OpenTcp.setObjectName("Btn_OpenTcp")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 201, 74))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_IP = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_IP.setEditable(True)
        self.comboBox_IP.setObjectName("comboBox_IP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_IP)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Port = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Port)
        self.comboBox_TCP = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_TCP.setEditable(False)
        self.comboBox_TCP.setObjectName("comboBox_TCP")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_TCP)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(440, 10, 351, 361))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_client = QtWidgets.QWidget()
        self.tab_client.setObjectName("tab_client")
        self.listView = QtWidgets.QListView(self.tab_client)
        self.listView.setGeometry(QtCore.QRect(0, 0, 341, 301))
        self.listView.setObjectName("listView")
        self.cbtn_all = QtWidgets.QCommandLinkButton(self.tab_client)
        self.cbtn_all.setGeometry(QtCore.QRect(0, 300, 101, 41))
        self.cbtn_all.setObjectName("cbtn_all")
        self.tabWidget.addTab(self.tab_client, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tbl_history = QtWidgets.QTableView(self.tab_2)
        self.tbl_history.setGeometry(QtCore.QRect(0, 0, 341, 331))
        self.tbl_history.setObjectName("tbl_history")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.File_Open = QtWidgets.QAction(MainWindow)
        self.File_Open.setStatusTip("")
        self.File_Open.setObjectName("File_Open")
        self.File_Close = QtWidgets.QAction(MainWindow)
        self.File_Close.setStatusTip("")
        self.File_Close.setObjectName("File_Close")
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.File_Open)
        self.menu_F.addAction(self.File_Close)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.File_Close.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络调试工具V1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "交互数据"))
        self.cbtn_clr.setText(_translate("MainWindow", "清空数据"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据发送"))
        self.textEdit_Send.setPlaceholderText(_translate("MainWindow", "请输入要发送的内容"))
        self.Btn_Send.setText(_translate("MainWindow", "发送数据"))
        self.checkBox_GapTime.setText(_translate("MainWindow", "定时发送"))
        self.checkBox_Hex.setText(_translate("MainWindow", "发送Hex字节"))
        self.label_4.setText(_translate("MainWindow", "时间"))
        self.lineEdit_GapTime.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "ms"))
        self.groupBox_3.setTitle(_translate("MainWindow", "网络连接设置"))
        self.Btn_OpenTcp.setText(_translate("MainWindow", "打开连接"))
        self.label.setText(_translate("MainWindow", "协议类型"))
        self.label_2.setText(_translate("MainWindow", "本机地址"))
        self.label_3.setText(_translate("MainWindow", "本机端口号"))
        self.lineEdit_Port.setText(_translate("MainWindow", "9000"))
        self.cbtn_all.setText(_translate("MainWindow", "全选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_client), _translate("MainWindow", "客户端列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "操作记录"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.File_Open.setText(_translate("MainWindow", "打开"))
        self.File_Close.setText(_translate("MainWindow", "退出"))
